### ISSUE TITLE
Dont duplicate texts across levels please

### ISSUE THREAD

**Issue by lb42** [COST-ELTeC/ELTeC-deu#13]
You seem to have copied all the texts from level0 into the level1 directory, but not removed them from level0. This will (wrongly) double the number of titles reported in the statistics, since the assumption is that if a title exists at level 1, it does not exist at level0. Also the texts in level1 should not have an encodingDesc which says they are at level0.

Please remove identical titles from one or other leveln directory and adjust the encodingDesc accordingly.

**Comment by LeKonArD** [comment]
Thanks, I was not aware of this, but have now removed the level0 files and adjusted the encodingDesc in level1.
