### ISSUE TITLE
The CETEIcean rendering doesn't work for DEU

### ISSUE THREAD

**Issue by christofs** [COST-ELTeC/ELTeC-deu#2]
Typical error message: 

XML Parsing Error: syntax error
Location: https://distantreading.github.io/ELTeC/deu/DEU022.html
Line Number 1, Column 1:
undefined
^

**Comment by lb42** [comment]
This happens because the HTML skeleton file is invalid or has not been regenerated. Which happens because I haven't rerun the "expose" script. Which happens because I was waiting for the errors in the headers to be fixed. As I still am.

**Comment by lb42** [comment]
Closing this as it's now fixed.
