### ISSUE TITLE
check DEU061

### ISSUE THREAD

**Issue by jberenike** [COST-ELTeC/ELTeC-deu#8]
the title for DEU061 didn't get copied into the TitleStudy spreadsheet. https://github.com/distantreading/WG1/tree/master/titlePilotStudy

You may want to have a look at the xml code.

**Comment by lb42** [comment]
That's probably because you didn't make your spreadsheet starting from the XML source! Have now fixed source and regenerated the index.html. Thanks for noticing/reporting the problem.
