### ISSUE TITLE
subtitles missing

### ISSUE THREAD

**Issue by jberenike** [COST-ELTeC/ELTeC-deu#9]
several entries for DEU miss subtitles. See TitleStudy https://github.com/distantreading/WG1/tree/master/titlePilotStudy --> spreadsheet "deu_jbh" (marked in red)

e.g. DEU070
"Schach von Wuthenow. Erzählung aus der Zeit des Regiments Gensdarmes."

**Comment by jberenike** [comment]
this work [ https://github.com/distantreading/WG1/tree/master/titlePilotStudy ] has shown that the DEU collection has not been well curated for the subtitles! Researching the original subtitles for the particular edition is a substantial task --- I have invested several hours, if not days, because otherwise annotation would not have made sense. However, there is a degree of uncertainty involved in my additions as I used diverse resources on the web and not the original printed edition.

**Comment by jberenike** [comment]
Apparently, only few subtitles are missing, if any (https://github.com/distantreading/WG1/issues/40#issuecomment-636524021 ).

**Comment by CarolinOdebrecht** [comment]
Check for the bibl-element. title-element is not specified in this sense in the XML files. I also checked for the English collection the bibl-element (source) and added subtitles.

**Comment by lb42** [comment]
You have to look at the right `<bibl>` element, of course: the one with @type='printSource' or (in a few cases which I am about to fix) 'firstEdition'. Otherwise you will get a lot of titles referring to some entity called Gutenberg!

**Comment by lb42** [comment]
Closing this as no correction seems necessary
